# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 18) do

  create_table "answer_records", :force => true do |t|
    t.column "problem",             :string
    t.column "decoded_answer",      :string
    t.column "start_time",          :datetime
    t.column "test_result_id",      :integer
    t.column "template_version_id", :integer
    t.column "section",             :string
    t.column "choices",             :integer
  end

  create_table "cutoff_scores", :force => true do |t|
    t.column "test_template_id",         :integer
    t.column "score",                    :float
    t.column "recommendation",           :string
    t.column "alternate_recommendation", :string
    t.column "seq_position",             :integer
    t.column "test_sequence_id",         :integer
    t.column "subsequence_id",           :integer
    t.column "fail_cutoff_score",        :integer
    t.column "pass_cutoff_score",        :integer
  end

  create_table "procedures", :force => true do |t|
    t.column "name",        :string
    t.column "text",        :text
    t.column "description", :string
  end

  create_table "recommendations", :force => true do |t|
    t.column "key_vector", :string
    t.column "rec",        :text
    t.column "tally",      :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "students", :force => true do |t|
    t.column "student_number", :string
    t.column "first_name",     :string
    t.column "last_name",      :string
    t.column "birth_date",     :date
    t.column "test_vector",    :string
    t.column "last_date",      :datetime
  end

  create_table "template_versions", :force => true do |t|
    t.column "version",          :integer
    t.column "template",         :text
    t.column "test_template_id", :integer
    t.column "histogram",        :text
    t.column "number_scores",    :integer
  end

  create_table "test_results", :force => true do |t|
    t.column "answers",             :string
    t.column "test_items",          :text
    t.column "score",               :float
    t.column "raw_score",           :integer
    t.column "status",              :string
    t.column "start_time",          :datetime
    t.column "student_id",          :integer
    t.column "template_version_id", :integer
    t.column "test_session_id",     :string
    t.column "cutoff_score_id",     :integer
  end

  create_table "test_sequences", :force => true do |t|
    t.column "name",                   :string
    t.column "description",            :string
    t.column "initial_recommendation", :text
    t.column "start_test_id",          :integer
    t.column "list_position",          :integer
  end

  create_table "test_sessions", :force => true do |t|
    t.column "status",           :string
    t.column "start_time",       :datetime
    t.column "student_id",       :integer
    t.column "location",         :string
    t.column "test_sequence_id", :integer
    t.column "start_test_id",    :integer
    t.column "parent_session",   :integer
    t.column "final_test",       :integer
    t.column "final_score",      :float
    t.column "processed",        :datetime
  end

  create_table "test_templates", :force => true do |t|
    t.column "name",                :string
    t.column "template_version_id", :integer
    t.column "description",         :string
    t.column "color",               :string,  :limit => 7
    t.column "code",                :string,  :limit => 4
    t.column "status",              :string,  :limit => 8, :default => "active"
  end

  create_table "users", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "user_name",  :string
    t.column "password",   :string
    t.column "role",       :string
    t.column "location",   :string
  end

end
